services:
  backend:
    build:
      context: .
      args:
        DATABASE_URL: 'postgresql://fabricio:postgres@db:5432/nestdb'
    container_name: nestjs-music-application
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - db
    command: sh -c "npx prisma migrate deploy && node dist/src/main"

  db:
    image: postgres:15
    container_name: nest_music_postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: fabricio
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestdb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
