version: '3.8'

services:
  db:
    image: postgres:15
    container_name: nest_music_postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: fabricio
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestdb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
